;; Plugins' permissions.
;; If flag is not found in plugin section, corresponding flag from "default" section is used.
;; If flag is not found in "default" section, it is assumed to be "yes".
;;
;; For setting individual plugin permissions you must write something like that:
;;
;; [ratio]
;; enabled = yes			;; also may be "user-defined", in this case user can control plugin's state from UI
;; canChangeToolbar = yes
;; canChangeMenu = yes
;; canChangeOptions = no
;; canChangeTabs = yes
;; canChangeColumns = yes
;; canChangeStatusBar = yes
;; canChangeCategory = yes
;; canBeShutdowned = yes

[default]
enabled = yes
canChangeToolbar = yes
canChangeMenu = yes
canChangeOptions = yes
canChangeTabs = yes
canChangeColumns = yes
canChangeStatusBar = yes
canChangeCategory = yes
canBeShutdowned = yes

[_xevent]
canBeShutdowned = no
enabled = yes

[_getdir]
canBeShutdowned = no
enabled = yes

[data]
enabled = false

[darkpal]
enabled = false

[rpc]
enabled = false

[autotools]
enabled = false

[xautotools]
enabled = user-defined

[cpuload]
enabled = _XIRVIK_USE_CPULOAD

[explorer]
enabled = user-defined

[feeds]
enabled = user-defined

[filedrop]
enabled = user-defined

[firewall]
enabled = _XIRVIK_USE_FIREWALL

[history]
enabled = _XIRVIK_USE_HISTORY

[rutracker_check]
enabled = user-defined

[mediainfo]
enabled = user-defined

[screenshots]
enabled = user-defined

[geoip]
enabled = user-defined

[ipad]
enabled = user-defined

[rss]
enabled = user-defined

[trafic]
enabled = _XIRVIK_USE_TRAFIC

[ratio]
enabled = user-defined

[unpack]
enabled = false

[xunpack]
enabled = user-defined

[xcreate]
enabled = user-defined

[create]
enabled = false

[check_port]
enabled = false

[choke]
enabled = false

[httprpc]
enabled = _XIRVIK_USE_HTTPRPC
;enabled = false

[multirpc]
enabled = _XIRVIK_USE_MULTIRPC
;enabled = true

[autodl-irssi]
enabled = _XIRVIK_USE_AUTODL_IRSSI

[chat]
enabled = _XIRVIK_USE_INTRASERVER_CHAT

[xshoutbox]
enabled = _XIRVIK_USE_SHOUTBOX

[xfreeservice]
enabled = _XIRVIK_USE_XFREESERVICE

[xpublicratiosanity]
enabled = _XIRVIK_USE_RATIOSANITY

[shoutbox]
enabled = false

[localnews]
enabled = _XIRVIK_USE_LOCALNEWS

[rutorrent-titlebar]
enabled = false

[_noty2]
enabled = false

[_noty]
enabled = true

[_cloudflare]
enabled = false

[chunks]
enabled = user-defined

[edit]
enabled = user-defined

[erasedata]
enabled = user-defined

[extsearch]
enabled = user-defined

[hints]
enabled = user-defined

[lookat]
enabled = user-defined

[xmpp]
enabled = user-defined

[xnfo]
enabled = user-defined

[tracklabels]
enabled = user-defined

[source]
enabled = user-defined

[show_peers_like_wtorrent]
enabled = user-defined

[seedingtime]
enabled = user-defined

[scheduler]
enabled = user-defined

[rssurlrewrite]
enabled = user-defined

[retrackers]
enabled = user-defined

[ratiomet]
enabled = user-defined

[loginmgr]
enabled = user-defined

[cookies]
enabled = user-defined

[diskspace]
enabled = user-defined

[ratiocolor]
enabled = user-defined
